// Complete Product Catalog for AMC Mart
// Product images sourced from official Mindray Animal Medical (mindrayanimal.com)

export interface Product {
  id: string;
  name: string;
  slug: string;
  category: string;
  categorySlug: string;
  subcategory?: string;
  subcategorySlug?: string;
  shortDescription: string;
  description?: string;
  keyFeatures: string[];
  systemCapabilities?: string[];
  speciesSupported?: string[];
  imageUrl: string;
  galleryImages?: string[];
  isFeatured?: boolean;
}

export interface Category {
  id: string;
  name: string;
  slug: string;
  description: string;
  imageUrl: string;
  subcategories?: Subcategory[];
}

export interface Subcategory {
  id: string;
  name: string;
  slug: string;
  description?: string;
}

// Official Mindray Animal Medical product images
const MINDRAY_IMAGES = {
  // Hematology Analyzers
  "bc-60r-vet": "https://www.mindrayanimal.com/n0/m4s0jp/250612/904/jpg/hq7dpel2.jpg",
  "bc-5000-vet": "https://www.mindrayanimal.com/n0/gflsvk/210713/144/jpg/ddv8qyge.jpg",
  "bc-30-vet": "https://www.mindrayanimal.com/n0/eddcje/210713/174/jpg/8sxcujby.jpg",
  "bc-20-vet": "https://www.mindrayanimal.com/n0/8el1aa/240923/760/jpg/9nd94otn.jpg",
  
  // Chemistry/Biochemistry Analyzers
  "vetxpert-cube": "https://www.mindrayanimal.com/n0/konywt/240829/660/jpg/g97yxtye.jpg",
  "vetxpert-c5": "https://www.mindrayanimal.com/n0/vrv9cd/240829/435/jpg/8cm6nbfo.jpg",
  "bs-240-vet": "https://www.mindrayanimal.com/n0/lzklvj/231128/463/jpg/dd0ddtni.jpg",
  
  // Immunology Analyzer
  "vetxpert-i3i5": "https://www.mindrayanimal.com/n0/d7f1z6/240829/243/jpg/049ifblr.jpg",
  
  // Urine Analyzer
  "ua-60v": "https://www.mindrayanimal.com/n0/x2uqff/220613/152/jpg/pfbdluxl.jpg",
  
  // Ultrasound - Cart Based
  "vetus-9": "https://www.mindrayanimal.com/n0/zeyqf1/220921/732/jpg/ram9c4at.jpg",
  "vetus-80": "https://www.mindrayanimal.com/n0/4xplhp/240829/267/jpg/lgzjmocb.jpg",
  "vetus-8": "https://www.mindrayanimal.com/n0/ey98cy/210713/528/jpg/1bv5yssm.jpg",
  "vetus-7": "https://www.mindrayanimal.com/n0/begmh7/210713/204/jpg/an0wivg8.jpg",
  "vetus-50": "https://www.mindrayanimal.com/n0/tdwlk3/231108/324/jpg/ik4a8dni.jpg",
  "vetus-5-exp": "https://www.mindrayanimal.com/n0/sml1tm/210713/788/jpg/muuaw35u.jpg",
  "vetus-5": "https://www.mindrayanimal.com/n0/g2nspd/210713/141/jpg/ebaags6g.jpg",
  
  // Ultrasound - Portable
  "vetus-e7": "https://www.mindrayanimal.com/n0/xw1qwn/211221/337/jpg/pxvmddmc.jpg",
  "vetus-eq": "https://www.mindrayanimal.com/n0/ss5ixf/230614/1/jpg/ljjv9ptt.jpg",
  "vetus-nova": "https://www.mindrayanimal.com/n0/qrajej/241105/933/jpg/sgqgaeen.jpg",
  "te5-vet": "https://www.mindrayanimal.com/n0/13wnm4/211105/280/jpg/5jtrfrrt.jpg",
  "z60-vet": "https://www.mindrayanimal.com/n0/xqccfb/210713/838/jpg/ffsooiqj.jpg",
  "dp-50-vet": "https://www.mindrayanimal.com/n0/fj1don/210713/463/jpg/fxe1fmk5.jpg",
  "dp-30-vet": "https://www.mindrayanimal.com/n0/u4nw5h/210713/667/jpg/qalez97m.jpg",
  "dp-10-vet": "https://www.mindrayanimal.com/n0/gyubws/210713/700/jpg/sjdbwug1.jpg",
  
  // Anesthesia Machines
  "wato-ex-65-pro-vet": "https://www.mindrayanimal.com/n0/ostgmk/250612/314/jpg/ne04ybbg.jpg",
  "wato-ex-35-vet": "https://www.mindrayanimal.com/n0/krutvq/210714/965/jpg/uyeje7qs.jpg",
  "wato-ex-20-vet": "https://www.mindrayanimal.com/n0/zmmwjo/210714/474/jpg/wkkg4w6h.jpg",
  "veta-5-plus": "https://www.mindrayanimal.com/n0/b2nra7/241107/192/jpg/1ys3ux3b.jpg",
  "veta-5": "https://www.mindrayanimal.com/n0/d42ho0/210714/444/jpg/yyj3zwta.jpg",
  "veta-3": "https://www.mindrayanimal.com/n0/d42ho0/210714/444/jpg/yyj3zwta.jpg",
  "veta-3x": "https://www.mindrayanimal.com/n0/qykita/240923/452/jpg/fg0jheqr.jpg",
  
  // Patient Monitoring
  "epm-12m-vet": "https://www.mindrayanimal.com/n0/edsehs/210713/451/jpg/bdwkzden.jpg",
  "pm60-vet": "https://www.mindrayanimal.com/n0/tj6sjo/210713/465/jpg/hrg140zt.jpg",
  "umed20-vet": "https://www.mindrayanimal.com/n0/jex07b/251103/443/jpg/iscrzzjp.jpg",
  "vetal-3": "https://www.mindrayanimal.com/n0/i0rwzk/240923/742/jpg/bzpl99ol.jpg",
  "vetinet-cms": "https://www.mindrayanimal.com/n0/nnimue/250708/371/jpg/80cnhgbz.jpg",
  
  // Infusion Pumps
  "benefusion-esp-evp-eds-vet": "https://www.mindrayanimal.com/n0/v2wdht/220705/354/jpg/eqd4ubbj.jpg",
  "benefusion-sp1-vet": "https://www.mindrayanimal.com/n0/pxll5m/220815/929/jpg/pqpdc6ee.jpg",
  "anifm-i3-s3": "https://www.mindrayanimal.com/n0/e3qh6p/251112/893/jpg/ygukabwm.jpg",
  "anifm-i1": "https://www.mindrayanimal.com/n0/gq4kiz/240923/49/jpg/pra9ljfv.jpg",
  
  // Telemetry
  "tms30-vet": "https://www.mindrayanimal.com/n0/blrvvx/250612/36/jpg/xahun6cc.jpg",
  
  // Ventilator
  "sv300-vet": "https://www.mindrayanimal.com/n0/mngpfw/250708/378/jpg/mtnqklyk.jpg",
  
  // Other Equipment
  "hyport-p20-30-vet": "https://www.mindrayanimal.com/n0/cnxs3o/240814/996/jpg/lbf1zdel.jpg",
  
  // Endoscopy
  "vetina-cs7": "https://www.mindrayanimal.com/n0/f9bjev/210830/100/jpg/9xo4zgxc.jpg",
  "vetina-cs3": "https://www.mindrayanimal.com/n0/mx9ubb/210901/361/jpg/95vhanyu.jpg",
  "vetina-es3": "https://www.mindrayanimal.com/n0/lw6tda/210901/951/jpg/bhzbyk6m.jpg",
  
  // X-Ray / Digital Radiography
  "vetix-s300": "https://www.mindrayanimal.com/n0/8i2utg/231213/799/jpg/fjnpggub.jpg",
  "vetix-p8": "https://www.mindrayanimal.com/n0/3f6ks4/220113/298/jpg/hzsxxqj3.jpg",
  
  // Surgical Lights
  "hyled-c50-vet": "https://www.mindrayanimal.com/n0/ldvimy/250612/483/jpg/u03z6jns.jpg",
  "veled-series": "https://www.mindrayanimal.com/n0/ruu15t/250627/966/jpg/yrj4vmh5.jpg",
  
  // Category images
  "category-lab": "https://www.mindrayanimal.com/n0/konywt/240829/660/jpg/g97yxtye.jpg",
  "category-life-support": "https://www.mindrayanimal.com/n0/ostgmk/250612/314/jpg/ne04ybbg.jpg",
  "category-imaging": "https://www.mindrayanimal.com/n0/zeyqf1/220921/732/jpg/ram9c4at.jpg",
  "category-radiology": "https://www.mindrayanimal.com/n0/8i2utg/231213/799/jpg/fjnpggub.jpg",
};

export const categories: Category[] = [
  {
    id: "lab-equipment",
    name: "Laboratory Equipment",
    slug: "laboratory-equipment",
    description: "Advanced diagnostic laboratory equipment for veterinary practices",
    imageUrl: MINDRAY_IMAGES["category-lab"],
    subcategories: [
      { id: "one-lab", name: "One Lab Analyzer", slug: "one-lab-analyzer" },
      { id: "biochemistry", name: "Biochemistry Analyzer", slug: "biochemistry-analyzer" },
      { id: "hematology", name: "Hematology Analyzer", slug: "hematology-analyzer" },
      { id: "immunology", name: "Immunology Analyzer", slug: "immunology-analyzer" },
      { id: "urine", name: "Other Laboratory Equipment", slug: "other-laboratory" },
    ],
  },
  {
    id: "life-support",
    name: "Life Support and Monitoring Equipment",
    slug: "life-support-monitoring",
    description: "Critical care and patient monitoring solutions",
    imageUrl: MINDRAY_IMAGES["category-life-support"],
    subcategories: [
      { id: "cms", name: "Central Monitoring System", slug: "central-monitoring" },
      { id: "anesthesia", name: "Anesthesia Machines", slug: "anesthesia-machines" },
      { id: "patient-monitor", name: "Patient Monitoring Systems", slug: "patient-monitoring" },
      { id: "infusion", name: "Infusion Pumps", slug: "infusion-pumps" },
      { id: "incubator", name: "Incubator ICU Machine", slug: "incubator-icu" },
      { id: "ventilator", name: "Ventilator", slug: "ventilator" },
      { id: "telemetry", name: "Telemetry", slug: "telemetry" },
      { id: "other-life", name: "Other Equipment", slug: "other-life-support" },
    ],
  },
  {
    id: "medical-imaging",
    name: "Medical Imaging Equipment",
    slug: "medical-imaging",
    description: "Advanced imaging solutions for accurate diagnostics",
    imageUrl: MINDRAY_IMAGES["category-imaging"],
    subcategories: [
      { id: "ultrasound-cart", name: "Ultrasound Machine - Cart Based", slug: "ultrasound-cart" },
      { id: "ultrasound-portable", name: "Ultrasound Machine - Portable", slug: "ultrasound-portable" },
      { id: "endoscopy-rigid", name: "Endoscopy Machine - Rigid", slug: "endoscopy-rigid" },
      { id: "endoscopy-flexible", name: "Endoscopy Machine - Flexible", slug: "endoscopy-flexible" },
    ],
  },
  {
    id: "radiology",
    name: "Radiology Equipment",
    slug: "radiology-equipment",
    description: "Digital radiography systems for veterinary imaging",
    imageUrl: MINDRAY_IMAGES["category-radiology"],
    subcategories: [
      { id: "xray", name: "X-Ray Machine", slug: "x-ray-machine" },
      { id: "dental-xray", name: "Dental X-Ray", slug: "dental-x-ray" },
    ],
  },
  {
    id: "lab-reagent",
    name: "Laboratory Reagent",
    slug: "laboratory-reagent",
    description: "High-quality reagents for diagnostic testing",
    imageUrl: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800",
    subcategories: [
      { id: "dry-reagent", name: "Dry Reagent", slug: "dry-reagent" },
      { id: "wet-reagent", name: "Wet Reagent", slug: "wet-reagent" },
    ],
  },
  {
    id: "surgical",
    name: "Surgical Equipment",
    slug: "surgical-equipment",
    description: "Professional surgical equipment and lighting",
    imageUrl: MINDRAY_IMAGES["hyled-c50-vet"],
    subcategories: [
      { id: "surgical-lights", name: "Surgical Lights", slug: "surgical-lights" },
    ],
  },
  {
    id: "vet-medical",
    name: "Vet Medical Equipment & Solution",
    slug: "vet-medical-equipment",
    description: "Comprehensive veterinary medical solutions",
    imageUrl: MINDRAY_IMAGES["epm-12m-vet"],
  },
  {
    id: "pet-accessories",
    name: "Pet Accessories",
    slug: "pet-accessories",
    description: "Quality accessories for pet care and travel",
    imageUrl: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800",
    subcategories: [
      { id: "medical-acc", name: "Pet Medical Accessories", slug: "pet-medical-accessories" },
      { id: "travel-acc", name: "Pet Travel Accessories", slug: "pet-travel-accessories" },
      { id: "other-acc", name: "Pet Other Accessories", slug: "pet-other-accessories" },
    ],
  },
];

export const products: Product[] = [
  // Laboratory Equipment - One Lab Analyzer
  {
    id: "vetxpert-cube",
    name: "vetXpert Cube",
    slug: "vetxpert-cube",
    category: "Laboratory Equipment",
    categorySlug: "laboratory-equipment",
    subcategory: "One Lab Analyzer",
    subcategorySlug: "one-lab-analyzer",
    shortDescription: "All-in-one veterinary laboratory analyzer for comprehensive diagnostics",
    keyFeatures: [
      "Integrated hematology, biochemistry, and immunology testing",
      "Compact benchtop design",
      "User-friendly touchscreen interface",
      "Rapid results with high accuracy",
      "Low sample volume requirements",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine", "Small mammals"],
    imageUrl: MINDRAY_IMAGES["vetxpert-cube"],
    isFeatured: true,
  },
  // Biochemistry Analyzers
  {
    id: "vetxpert-c5",
    name: "vetXpert C5",
    slug: "vetxpert-c5",
    category: "Laboratory Equipment",
    categorySlug: "laboratory-equipment",
    subcategory: "Biochemistry Analyzer",
    subcategorySlug: "biochemistry-analyzer",
    shortDescription: "Advanced biochemistry analyzer for veterinary clinical chemistry",
    keyFeatures: [
      "High throughput of up to 200 tests per hour",
      "Wide test menu for comprehensive panels",
      "Automatic sample handling",
      "Built-in quality control",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine", "Swine", "Avian"],
    imageUrl: MINDRAY_IMAGES["vetxpert-c5"],
    isFeatured: true,
  },
  {
    id: "bs-240-vet",
    name: "BS-240 Vet",
    slug: "bs-240-vet",
    category: "Laboratory Equipment",
    categorySlug: "laboratory-equipment",
    subcategory: "Biochemistry Analyzer",
    subcategorySlug: "biochemistry-analyzer",
    shortDescription: "Fully automated clinical chemistry analyzer for veterinary applications",
    keyFeatures: [
      "240 tests per hour throughput",
      "80 onboard reagent positions",
      "ISE module option",
      "Comprehensive veterinary test panel",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine"],
    imageUrl: MINDRAY_IMAGES["bs-240-vet"],
  },
  // Hematology Analyzers
  {
    id: "bc-60r-vet",
    name: "BC-60R Vet",
    slug: "bc-60r-vet",
    category: "Laboratory Equipment",
    categorySlug: "laboratory-equipment",
    subcategory: "Hematology Analyzer",
    subcategorySlug: "hematology-analyzer",
    shortDescription: "6-part differential hematology analyzer with reticulocyte counting",
    keyFeatures: [
      "6-part differential analysis",
      "Reticulocyte counting capability",
      "Up to 60 samples per hour",
      "Species-specific analysis modes",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine", "Small mammals"],
    imageUrl: MINDRAY_IMAGES["bc-60r-vet"],
    isFeatured: true,
  },
  {
    id: "bc-5000-vet",
    name: "BC-5000 Vet",
    slug: "bc-5000-vet",
    category: "Laboratory Equipment",
    categorySlug: "laboratory-equipment",
    subcategory: "Hematology Analyzer",
    subcategorySlug: "hematology-analyzer",
    shortDescription: "High-performance 5-part hematology analyzer for busy veterinary practices",
    keyFeatures: [
      "5-part white blood cell differential",
      "Up to 60 samples per hour",
      "Automatic sample loading",
      "Advanced data management",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine"],
    imageUrl: MINDRAY_IMAGES["bc-5000-vet"],
  },
  {
    id: "bc-30-vet",
    name: "BC-30 Vet",
    slug: "bc-30-vet",
    category: "Laboratory Equipment",
    categorySlug: "laboratory-equipment",
    subcategory: "Hematology Analyzer",
    subcategorySlug: "hematology-analyzer",
    shortDescription: "Compact 3-part hematology analyzer for veterinary clinics",
    keyFeatures: [
      "3-part differential",
      "30 samples per hour",
      "Compact design",
      "Easy maintenance",
    ],
    speciesSupported: ["Dog", "Cat", "Horse"],
    imageUrl: MINDRAY_IMAGES["bc-30-vet"],
  },
  {
    id: "bc-20-vet",
    name: "BC-20 Vet",
    slug: "bc-20-vet",
    category: "Laboratory Equipment",
    categorySlug: "laboratory-equipment",
    subcategory: "Hematology Analyzer",
    subcategorySlug: "hematology-analyzer",
    shortDescription: "Entry-level 3-part hematology analyzer for small practices",
    keyFeatures: [
      "3-part differential analysis",
      "20 samples per hour",
      "Low reagent consumption",
      "Simple operation",
    ],
    speciesSupported: ["Dog", "Cat"],
    imageUrl: MINDRAY_IMAGES["bc-20-vet"],
  },
  // Immunology Analyzer
  {
    id: "vetxpert-i3i5",
    name: "vetXpert I3I5",
    slug: "vetxpert-i3i5",
    category: "Laboratory Equipment",
    categorySlug: "laboratory-equipment",
    subcategory: "Immunology Analyzer",
    subcategorySlug: "immunology-analyzer",
    shortDescription: "Immunofluorescence analyzer for veterinary diagnostics",
    keyFeatures: [
      "Immunofluorescence technology",
      "Wide test menu including hormones and biomarkers",
      "Rapid turnaround time",
      "Easy-to-use interface",
    ],
    speciesSupported: ["Dog", "Cat", "Horse"],
    imageUrl: MINDRAY_IMAGES["vetxpert-i3i5"],
  },
  // Urine Analyzer
  {
    id: "ua-60v",
    name: "UA-60V",
    slug: "ua-60v",
    category: "Laboratory Equipment",
    categorySlug: "laboratory-equipment",
    subcategory: "Other Laboratory Equipment",
    subcategorySlug: "other-laboratory",
    shortDescription: "Automated urine analyzer for veterinary urinalysis",
    keyFeatures: [
      "Fully automated urine analysis",
      "Up to 60 samples per hour",
      "Comprehensive test parameters",
      "Veterinary-specific calibration",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine"],
    imageUrl: MINDRAY_IMAGES["ua-60v"],
  },
  // Life Support - Central Monitoring
  {
    id: "vetinet-cms",
    name: "VetiNet CMS",
    slug: "vetinet-cms",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Central Monitoring System",
    subcategorySlug: "central-monitoring",
    shortDescription: "Comprehensive central monitoring system for veterinary ICU",
    keyFeatures: [
      "Multi-bed monitoring capability",
      "Real-time data streaming",
      "Alert and alarm management",
      "Network integration",
    ],
    imageUrl: MINDRAY_IMAGES["vetinet-cms"],
    isFeatured: true,
  },
  // Anesthesia Machines
  {
    id: "wato-ex-65-pro-vet",
    name: "WATO EX-65 Pro Vet",
    slug: "wato-ex-65-pro-vet",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Anesthesia Machines",
    subcategorySlug: "anesthesia-machines",
    shortDescription: "Premium veterinary anesthesia workstation with advanced ventilation",
    keyFeatures: [
      "Advanced ventilation modes",
      "Integrated patient monitoring",
      "Electronic gas mixing",
      "Comprehensive safety features",
    ],
    speciesSupported: ["Small animals", "Large animals", "Equine"],
    imageUrl: MINDRAY_IMAGES["wato-ex-65-pro-vet"],
    isFeatured: true,
  },
  {
    id: "wato-ex-35-vet",
    name: "WATO EX-35Vet",
    slug: "wato-ex-35-vet",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Anesthesia Machines",
    subcategorySlug: "anesthesia-machines",
    shortDescription: "Mid-range veterinary anesthesia machine with reliable performance",
    keyFeatures: [
      "Multiple ventilation modes",
      "Compact footprint",
      "Easy maintenance",
      "Reliable gas delivery",
    ],
    speciesSupported: ["Dog", "Cat", "Small mammals"],
    imageUrl: MINDRAY_IMAGES["wato-ex-35-vet"],
  },
  {
    id: "wato-ex-20-vet",
    name: "WATO EX-20Vet",
    slug: "wato-ex-20-vet",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Anesthesia Machines",
    subcategorySlug: "anesthesia-machines",
    shortDescription: "Entry-level veterinary anesthesia machine for small clinics",
    keyFeatures: [
      "Basic ventilation modes",
      "Compact design",
      "Cost-effective solution",
      "Easy operation",
    ],
    speciesSupported: ["Dog", "Cat"],
    imageUrl: MINDRAY_IMAGES["wato-ex-20-vet"],
  },
  {
    id: "veta-5-plus",
    name: "Veta 5 Plus",
    slug: "veta-5-plus",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Anesthesia Machines",
    subcategorySlug: "anesthesia-machines",
    shortDescription: "Advanced portable veterinary anesthesia system",
    keyFeatures: [
      "Portable design",
      "Multiple species support",
      "Advanced safety features",
      "Battery backup option",
    ],
    speciesSupported: ["Dog", "Cat", "Small mammals", "Exotic"],
    imageUrl: MINDRAY_IMAGES["veta-5-plus"],
  },
  {
    id: "veta-5",
    name: "Veta 5",
    slug: "veta-5",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Anesthesia Machines",
    subcategorySlug: "anesthesia-machines",
    shortDescription: "Reliable veterinary anesthesia system for daily use",
    keyFeatures: [
      "Robust construction",
      "Intuitive controls",
      "Low maintenance",
      "Consistent performance",
    ],
    speciesSupported: ["Dog", "Cat"],
    imageUrl: MINDRAY_IMAGES["veta-5"],
  },
  {
    id: "veta-3",
    name: "Veta 3",
    slug: "veta-3",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Anesthesia Machines",
    subcategorySlug: "anesthesia-machines",
    shortDescription: "Compact anesthesia system for veterinary practices",
    keyFeatures: [
      "Space-saving design",
      "Essential features",
      "Easy setup",
      "Affordable solution",
    ],
    speciesSupported: ["Dog", "Cat"],
    imageUrl: MINDRAY_IMAGES["veta-3"],
  },
  {
    id: "veta-3x",
    name: "Veta 3x",
    slug: "veta-3x",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Anesthesia Machines",
    subcategorySlug: "anesthesia-machines",
    shortDescription: "Enhanced version of Veta 3 with extended capabilities",
    keyFeatures: [
      "Extended features",
      "Improved monitoring",
      "Compact design",
      "Enhanced reliability",
    ],
    speciesSupported: ["Dog", "Cat", "Small mammals"],
    imageUrl: MINDRAY_IMAGES["veta-3x"],
  },
  // Patient Monitoring
  {
    id: "epm-12m-vet",
    name: "ePM 12M Vet",
    slug: "epm-12m-vet",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Patient Monitoring Systems",
    subcategorySlug: "patient-monitoring",
    shortDescription: "12-inch touchscreen veterinary patient monitor",
    keyFeatures: [
      "12-inch high-resolution display",
      "Multi-parameter monitoring",
      "Touchscreen interface",
      "Network connectivity",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine"],
    imageUrl: MINDRAY_IMAGES["epm-12m-vet"],
    isFeatured: true,
  },
  {
    id: "pm60-vet",
    name: "PM60 Vet",
    slug: "pm60-vet",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Patient Monitoring Systems",
    subcategorySlug: "patient-monitoring",
    shortDescription: "Portable pulse oximeter for veterinary use",
    keyFeatures: [
      "Handheld portable design",
      "SpO2 and pulse rate monitoring",
      "Veterinary-specific probes",
      "Long battery life",
    ],
    speciesSupported: ["Dog", "Cat", "Small mammals"],
    imageUrl: MINDRAY_IMAGES["pm60-vet"],
  },
  {
    id: "umed20-vet",
    name: "uMED20 Vet",
    slug: "umed20-vet",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Patient Monitoring Systems",
    subcategorySlug: "patient-monitoring",
    shortDescription: "Compact multi-parameter veterinary monitor",
    keyFeatures: [
      "Compact and lightweight",
      "Essential monitoring parameters",
      "Easy transport",
      "Quick setup",
    ],
    speciesSupported: ["Dog", "Cat"],
    imageUrl: MINDRAY_IMAGES["umed20-vet"],
  },
  {
    id: "vetal-3",
    name: "Vetal 3",
    slug: "vetal-3",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Patient Monitoring Systems",
    subcategorySlug: "patient-monitoring",
    shortDescription: "Basic veterinary patient monitor for clinics",
    keyFeatures: [
      "Essential parameters",
      "Affordable solution",
      "Simple interface",
      "Reliable performance",
    ],
    speciesSupported: ["Dog", "Cat"],
    imageUrl: MINDRAY_IMAGES["vetal-3"],
  },
  // Infusion Pumps
  {
    id: "benefusion-esp-evp-eds-vet",
    name: "BeneFusion eSP/eVP/eDS Vet",
    slug: "benefusion-esp-evp-eds-vet",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Infusion Pumps",
    subcategorySlug: "infusion-pumps",
    shortDescription: "Advanced modular infusion system for veterinary critical care",
    keyFeatures: [
      "Modular design",
      "High precision delivery",
      "Drug library support",
      "Dose error reduction system",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine"],
    imageUrl: MINDRAY_IMAGES["benefusion-esp-evp-eds-vet"],
  },
  {
    id: "benefusion-sp1-vet",
    name: "BeneFusion SP1 Vet",
    slug: "benefusion-sp1-vet",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Infusion Pumps",
    subcategorySlug: "infusion-pumps",
    shortDescription: "Single-channel syringe pump for precise medication delivery",
    keyFeatures: [
      "High accuracy",
      "Wide syringe compatibility",
      "Clear display",
      "Alarm system",
    ],
    speciesSupported: ["Dog", "Cat", "Small mammals"],
    imageUrl: MINDRAY_IMAGES["benefusion-sp1-vet"],
  },
  {
    id: "anifm-i3-s3",
    name: "AniFM I3/S3",
    slug: "anifm-i3-s3",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Infusion Pumps",
    subcategorySlug: "infusion-pumps",
    shortDescription: "Veterinary-specific infusion pump system",
    keyFeatures: [
      "Veterinary optimized",
      "Flow rate accuracy",
      "Multiple infusion modes",
      "Intuitive operation",
    ],
    speciesSupported: ["Dog", "Cat", "Horse"],
    imageUrl: MINDRAY_IMAGES["anifm-i3-s3"],
  },
  {
    id: "anifm-i1",
    name: "AniFM I1",
    slug: "anifm-i1",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Infusion Pumps",
    subcategorySlug: "infusion-pumps",
    shortDescription: "Entry-level veterinary infusion pump",
    keyFeatures: [
      "Simple operation",
      "Reliable performance",
      "Compact design",
      "Cost-effective",
    ],
    speciesSupported: ["Dog", "Cat"],
    imageUrl: MINDRAY_IMAGES["anifm-i1"],
  },
  // Incubator
  {
    id: "aeolus-uc-1803",
    name: "Aeolus UC-1803",
    slug: "aeolus-uc-1803",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Incubator ICU Machine",
    subcategorySlug: "incubator-icu",
    shortDescription: "Veterinary ICU incubator for critical care of small animals",
    keyFeatures: [
      "Precise temperature control",
      "Humidity management",
      "Oxygen concentration control",
      "Easy cleaning and maintenance",
    ],
    speciesSupported: ["Puppies", "Kittens", "Small mammals", "Birds"],
    imageUrl: MINDRAY_IMAGES["epm-12m-vet"], // Using similar equipment image
  },
  // Ventilator
  {
    id: "sv300-vet",
    name: "SV300 Vet",
    slug: "sv300-vet",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Ventilator",
    subcategorySlug: "ventilator",
    shortDescription: "Advanced veterinary ventilator for critical respiratory support",
    keyFeatures: [
      "Multiple ventilation modes",
      "High-precision delivery",
      "Comprehensive monitoring",
      "Species-specific settings",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine"],
    imageUrl: MINDRAY_IMAGES["sv300-vet"],
  },
  // Telemetry
  {
    id: "tms30-vet",
    name: "TMS30 Vet",
    slug: "tms30-vet",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Telemetry",
    subcategorySlug: "telemetry",
    shortDescription: "Wireless telemetry system for mobile patient monitoring",
    keyFeatures: [
      "Wireless monitoring",
      "Multi-patient support",
      "Long-range transmission",
      "Central station integration",
    ],
    speciesSupported: ["Dog", "Cat", "Horse"],
    imageUrl: MINDRAY_IMAGES["tms30-vet"],
  },
  // Other Life Support
  {
    id: "hyport-p20-30-vet",
    name: "HyPort P20/30 Vet",
    slug: "hyport-p20-30-vet",
    category: "Life Support and Monitoring Equipment",
    categorySlug: "life-support-monitoring",
    subcategory: "Other Equipment",
    subcategorySlug: "other-life-support",
    shortDescription: "Portable oxygen concentrator for veterinary emergency care",
    keyFeatures: [
      "Portable design",
      "High flow output",
      "Battery operation",
      "Emergency ready",
    ],
    speciesSupported: ["Dog", "Cat", "Small mammals"],
    imageUrl: MINDRAY_IMAGES["hyport-p20-30-vet"],
  },
  // Ultrasound - Cart Based
  {
    id: "vetus-9",
    name: "Vetus 9",
    slug: "vetus-9",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Ultrasound Machine - Cart Based",
    subcategorySlug: "ultrasound-cart",
    shortDescription: "Premium cart-based veterinary ultrasound system",
    keyFeatures: [
      "High-resolution imaging",
      "Advanced Doppler capabilities",
      "Large touchscreen display",
      "Comprehensive measurement package",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine", "Exotic"],
    imageUrl: MINDRAY_IMAGES["vetus-9"],
    isFeatured: true,
  },
  {
    id: "vetus-80",
    name: "Vetus 80",
    slug: "vetus-80",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Ultrasound Machine - Cart Based",
    subcategorySlug: "ultrasound-cart",
    shortDescription: "High-performance cart-based ultrasound for veterinary imaging",
    keyFeatures: [
      "Exceptional image quality",
      "Color Doppler imaging",
      "Veterinary-optimized presets",
      "Ergonomic cart design",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine"],
    imageUrl: MINDRAY_IMAGES["vetus-80"],
  },
  {
    id: "vetus-8",
    name: "Vetus 8",
    slug: "vetus-8",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Ultrasound Machine - Cart Based",
    subcategorySlug: "ultrasound-cart",
    shortDescription: "Versatile cart-based ultrasound for diverse veterinary applications",
    keyFeatures: [
      "Excellent image clarity",
      "Multiple probe compatibility",
      "User-friendly interface",
      "Network connectivity",
    ],
    speciesSupported: ["Dog", "Cat", "Horse"],
    imageUrl: MINDRAY_IMAGES["vetus-8"],
  },
  {
    id: "vetus-7",
    name: "Vetus 7",
    slug: "vetus-7",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Ultrasound Machine - Cart Based",
    subcategorySlug: "ultrasound-cart",
    shortDescription: "Reliable cart-based ultrasound for busy veterinary clinics",
    keyFeatures: [
      "Clear imaging",
      "Fast startup",
      "Durable construction",
      "Easy maintenance",
    ],
    speciesSupported: ["Dog", "Cat", "Horse"],
    imageUrl: MINDRAY_IMAGES["vetus-7"],
  },
  // Ultrasound - Portable
  {
    id: "vetus-50",
    name: "Vetus 50",
    slug: "vetus-50",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Ultrasound Machine - Portable",
    subcategorySlug: "ultrasound-portable",
    shortDescription: "Premium portable ultrasound for field and clinic use",
    keyFeatures: [
      "Lightweight portable design",
      "High image quality",
      "Long battery life",
      "Multiple probe options",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine"],
    imageUrl: MINDRAY_IMAGES["vetus-50"],
  },
  {
    id: "vetus-5",
    name: "Vetus 5",
    slug: "vetus-5",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Ultrasound Machine - Portable",
    subcategorySlug: "ultrasound-portable",
    shortDescription: "Compact portable ultrasound for veterinary diagnostics",
    keyFeatures: [
      "Ultra-portable design",
      "Clear imaging",
      "Quick setup",
      "Rugged construction",
    ],
    speciesSupported: ["Dog", "Cat", "Small mammals"],
    imageUrl: MINDRAY_IMAGES["vetus-5"],
  },
  {
    id: "vetus-5-exp",
    name: "Vetus 5 Exp",
    slug: "vetus-5-exp",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Ultrasound Machine - Portable",
    subcategorySlug: "ultrasound-portable",
    shortDescription: "Enhanced portable ultrasound with expanded features",
    keyFeatures: [
      "Expanded measurement package",
      "Enhanced imaging modes",
      "Portable convenience",
      "Extended probe compatibility",
    ],
    speciesSupported: ["Dog", "Cat", "Horse"],
    imageUrl: MINDRAY_IMAGES["vetus-5-exp"],
  },
  {
    id: "vetus-nova",
    name: "Vetus NOVA",
    slug: "vetus-nova",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Ultrasound Machine - Portable",
    subcategorySlug: "ultrasound-portable",
    shortDescription: "Next-generation portable veterinary ultrasound",
    keyFeatures: [
      "Latest imaging technology",
      "AI-assisted features",
      "Sleek portable design",
      "Cloud connectivity",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine", "Exotic"],
    imageUrl: MINDRAY_IMAGES["vetus-nova"],
    isFeatured: true,
  },
  {
    id: "vetus-e7",
    name: "Vetus E7",
    slug: "vetus-e7",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Ultrasound Machine - Portable",
    subcategorySlug: "ultrasound-portable",
    shortDescription: "Entry-level portable ultrasound for veterinary practices",
    keyFeatures: [
      "Affordable solution",
      "Easy operation",
      "Portable design",
      "Essential features",
    ],
    speciesSupported: ["Dog", "Cat"],
    imageUrl: MINDRAY_IMAGES["vetus-e7"],
  },
  {
    id: "vetus-eq",
    name: "Vetus EQ",
    slug: "vetus-eq",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Ultrasound Machine - Portable",
    subcategorySlug: "ultrasound-portable",
    shortDescription: "Equine-optimized portable ultrasound system",
    keyFeatures: [
      "Equine-specific presets",
      "Rugged field design",
      "Large display",
      "Extended battery life",
    ],
    speciesSupported: ["Horse", "Large animals"],
    imageUrl: MINDRAY_IMAGES["vetus-eq"],
  },
  {
    id: "te5-vet",
    name: "TE5 Vet",
    slug: "te5-vet",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Ultrasound Machine - Portable",
    subcategorySlug: "ultrasound-portable",
    shortDescription: "Tablet-style veterinary ultrasound for maximum portability",
    keyFeatures: [
      "Tablet form factor",
      "Touchscreen operation",
      "Wireless probes available",
      "Cloud backup",
    ],
    speciesSupported: ["Dog", "Cat", "Small mammals"],
    imageUrl: MINDRAY_IMAGES["te5-vet"],
  },
  {
    id: "z60-vet",
    name: "Z60 Vet",
    slug: "z60-vet",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Ultrasound Machine - Portable",
    subcategorySlug: "ultrasound-portable",
    shortDescription: "Versatile portable ultrasound with advanced features",
    keyFeatures: [
      "Advanced imaging modes",
      "Portable laptop design",
      "High-resolution display",
      "Multi-species support",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine"],
    imageUrl: MINDRAY_IMAGES["z60-vet"],
  },
  {
    id: "dp-50-vet",
    name: "DP-50 Vet",
    slug: "dp-50-vet",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Ultrasound Machine - Portable",
    subcategorySlug: "ultrasound-portable",
    shortDescription: "Mid-range portable ultrasound for veterinary clinics",
    keyFeatures: [
      "Good image quality",
      "Portable design",
      "Multiple applications",
      "Affordable pricing",
    ],
    speciesSupported: ["Dog", "Cat", "Horse"],
    imageUrl: MINDRAY_IMAGES["dp-50-vet"],
  },
  {
    id: "dp-30-vet",
    name: "DP-30 Vet",
    slug: "dp-30-vet",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Ultrasound Machine - Portable",
    subcategorySlug: "ultrasound-portable",
    shortDescription: "Compact portable ultrasound for basic diagnostics",
    keyFeatures: [
      "Compact size",
      "Easy to use",
      "Basic imaging",
      "Budget-friendly",
    ],
    speciesSupported: ["Dog", "Cat"],
    imageUrl: MINDRAY_IMAGES["dp-30-vet"],
  },
  {
    id: "dp-10-vet",
    name: "DP-10Vet",
    slug: "dp-10-vet",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Ultrasound Machine - Portable",
    subcategorySlug: "ultrasound-portable",
    shortDescription: "Entry-level portable ultrasound for small practices",
    keyFeatures: [
      "Entry-level pricing",
      "Essential features",
      "Portable convenience",
      "Simple operation",
    ],
    speciesSupported: ["Dog", "Cat"],
    imageUrl: MINDRAY_IMAGES["dp-10-vet"],
  },
  // Endoscopy - Rigid
  {
    id: "vetina-cs7",
    name: "Vetina CS7",
    slug: "vetina-cs7",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Endoscopy Machine - Rigid",
    subcategorySlug: "endoscopy-rigid",
    shortDescription: "Premium rigid endoscopy system for veterinary surgery",
    keyFeatures: [
      "HD visualization",
      "LED light source",
      "Complete instrument set",
      "Ergonomic design",
    ],
    speciesSupported: ["Dog", "Cat", "Horse"],
    imageUrl: MINDRAY_IMAGES["vetina-cs7"],
  },
  {
    id: "vetina-cs3",
    name: "Vetina CS3",
    slug: "vetina-cs3",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Endoscopy Machine - Rigid",
    subcategorySlug: "endoscopy-rigid",
    shortDescription: "Standard rigid endoscopy system for veterinary procedures",
    keyFeatures: [
      "Clear imaging",
      "Reliable performance",
      "Essential instruments included",
      "Easy maintenance",
    ],
    speciesSupported: ["Dog", "Cat"],
    imageUrl: MINDRAY_IMAGES["vetina-cs3"],
  },
  // Endoscopy - Flexible
  {
    id: "vetina-es3",
    name: "Vetina ES3",
    slug: "vetina-es3",
    category: "Medical Imaging Equipment",
    categorySlug: "medical-imaging",
    subcategory: "Endoscopy Machine - Flexible",
    subcategorySlug: "endoscopy-flexible",
    shortDescription: "Flexible video endoscopy system for GI diagnostics",
    keyFeatures: [
      "Flexible insertion tube",
      "Video documentation",
      "Multiple diameter options",
      "Biopsy capability",
    ],
    speciesSupported: ["Dog", "Cat", "Horse"],
    imageUrl: MINDRAY_IMAGES["vetina-es3"],
  },
  // X-Ray
  {
    id: "digital-dr-vet",
    name: "VetiX S300",
    slug: "digital-dr-vet",
    category: "Radiology Equipment",
    categorySlug: "radiology-equipment",
    subcategory: "X-Ray Machine",
    subcategorySlug: "x-ray-machine",
    shortDescription: "Complete digital radiography system for veterinary imaging",
    keyFeatures: [
      "High-resolution digital detector",
      "Fast image acquisition",
      "Veterinary-specific software",
      "DICOM compatible",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine", "Exotic"],
    imageUrl: MINDRAY_IMAGES["vetix-s300"],
    isFeatured: true,
  },
  {
    id: "portable-xray-vet",
    name: "VetiX P8",
    slug: "portable-xray-vet",
    category: "Radiology Equipment",
    categorySlug: "radiology-equipment",
    subcategory: "X-Ray Machine",
    subcategorySlug: "x-ray-machine",
    shortDescription: "Lightweight portable X-ray for field and emergency use",
    keyFeatures: [
      "Portable battery operation",
      "Lightweight design",
      "Quick imaging",
      "Easy transport",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine"],
    imageUrl: MINDRAY_IMAGES["vetix-p8"],
  },
  // Dental X-Ray
  {
    id: "dental-xray-vet",
    name: "Veterinary Dental X-Ray System",
    slug: "dental-xray-vet",
    category: "Radiology Equipment",
    categorySlug: "radiology-equipment",
    subcategory: "Dental X-Ray",
    subcategorySlug: "dental-x-ray",
    shortDescription: "Dedicated dental radiography for veterinary dentistry",
    keyFeatures: [
      "Intraoral sensor",
      "High-resolution dental imaging",
      "Veterinary dental software",
      "Compact design",
    ],
    speciesSupported: ["Dog", "Cat", "Horse"],
    imageUrl: MINDRAY_IMAGES["vetix-p8"], // Using portable X-ray image as similar
  },
  // Laboratory Reagent
  {
    id: "dry-reagent-kit",
    name: "Dry Reagent Diagnostic Kit",
    slug: "dry-reagent-kit",
    category: "Laboratory Reagent",
    categorySlug: "laboratory-reagent",
    subcategory: "Dry Reagent",
    subcategorySlug: "dry-reagent",
    shortDescription: "Comprehensive dry chemistry reagent panels for veterinary diagnostics",
    keyFeatures: [
      "Long shelf life",
      "Room temperature storage",
      "Wide test menu",
      "Quality controlled",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine"],
    imageUrl: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800",
  },
  {
    id: "wet-reagent-kit",
    name: "Wet Reagent Diagnostic Kit",
    slug: "wet-reagent-kit",
    category: "Laboratory Reagent",
    categorySlug: "laboratory-reagent",
    subcategory: "Wet Reagent",
    subcategorySlug: "wet-reagent",
    shortDescription: "Liquid reagents for high-volume veterinary laboratory testing",
    keyFeatures: [
      "High precision",
      "Large volume efficiency",
      "Comprehensive panels",
      "Analyzer compatible",
    ],
    speciesSupported: ["Dog", "Cat", "Horse", "Bovine", "Swine"],
    imageUrl: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800",
  },
  // Surgical Lights
  {
    id: "led-surgical-light",
    name: "HyLED C50 Vet",
    slug: "led-surgical-light",
    category: "Surgical Equipment",
    categorySlug: "surgical-equipment",
    subcategory: "Surgical Lights",
    subcategorySlug: "surgical-lights",
    shortDescription: "High-intensity LED surgical lighting for veterinary operating rooms",
    keyFeatures: [
      "Cool LED technology",
      "Adjustable intensity",
      "Shadow reduction",
      "Long lifespan",
    ],
    imageUrl: MINDRAY_IMAGES["hyled-c50-vet"],
  },
  {
    id: "veled-surgical-light",
    name: "VeLED Series",
    slug: "veled-surgical-light",
    category: "Surgical Equipment",
    categorySlug: "surgical-equipment",
    subcategory: "Surgical Lights",
    subcategorySlug: "surgical-lights",
    shortDescription: "Versatile LED surgical lighting system for various procedures",
    keyFeatures: [
      "Multiple light head options",
      "Adjustable color temperature",
      "Easy positioning",
      "Energy efficient",
    ],
    imageUrl: MINDRAY_IMAGES["veled-series"],
  },
  // Pet Accessories
  {
    id: "pet-medical-kit",
    name: "Pet Medical Accessories Kit",
    slug: "pet-medical-kit",
    category: "Pet Accessories",
    categorySlug: "pet-accessories",
    subcategory: "Pet Medical Accessories",
    subcategorySlug: "pet-medical-accessories",
    shortDescription: "Essential medical accessories for pet care at home",
    keyFeatures: [
      "First aid supplies",
      "Medication dispensers",
      "Recovery aids",
      "Quality materials",
    ],
    imageUrl: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800",
  },
  {
    id: "pet-travel-kit",
    name: "Pet Travel Accessories Kit",
    slug: "pet-travel-kit",
    category: "Pet Accessories",
    categorySlug: "pet-accessories",
    subcategory: "Pet Travel Accessories",
    subcategorySlug: "pet-travel-accessories",
    shortDescription: "Complete travel accessories for pet owners on the go",
    keyFeatures: [
      "Travel carriers",
      "Portable bowls",
      "Safety harnesses",
      "Travel comfort items",
    ],
    imageUrl: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800",
  },
  {
    id: "pet-other-accessories",
    name: "Pet Care Accessories",
    slug: "pet-other-accessories-kit",
    category: "Pet Accessories",
    categorySlug: "pet-accessories",
    subcategory: "Pet Other Accessories",
    subcategorySlug: "pet-other-accessories",
    shortDescription: "General pet care accessories for everyday use",
    keyFeatures: [
      "Grooming tools",
      "Feeding accessories",
      "Comfort items",
      "Training aids",
    ],
    imageUrl: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800",
  },
];

export const getProductsByCategory = (categorySlug: string): Product[] => {
  return products.filter(p => p.categorySlug === categorySlug);
};

export const getProductsBySubcategory = (subcategorySlug: string): Product[] => {
  return products.filter(p => p.subcategorySlug === subcategorySlug);
};

export const getProductBySlug = (slug: string): Product | undefined => {
  return products.find(p => p.slug === slug);
};

export const getCategoryBySlug = (slug: string): Category | undefined => {
  return categories.find(c => c.slug === slug);
};

export const getFeaturedProducts = (): Product[] => {
  return products.filter(p => p.isFeatured);
};
